using SQLite;
namespace CFSessionDB.Model
{
    public class Session
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }// this is autogenerated and primary key
        public string SessionTitle { get; set; }
        public string SessionDescription { get; set; }
        // constructor
        public Session()
        {
        }
        //constructor
        public Session(string title, string description)
        {
            SessionTitle = title;
            SessionDescription = description;
        }
    }
}
